In [24]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np


from pathlib import Path
from typing import List

In [25]:
data_path = Path("..") / "Fantasy-Premier-League" / "data"

In [26]:
seasons = sorted([
    p.name for p in data_path.iterdir()
    if p.is_dir() and p.name[0].isdigit()
])
print(seasons)

['2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24', '2024-25', '2025-26']

In [27]:
seasons = ['2021-22', '2022-23', '2023-24', '2024-25', '2025-26']

In [28]:
def data_import(season_list: List[str]) -> pd.DataFrame:
    gws = np.arange(1, 39)
    dfs = []
    content = Path("..")

    for season in season_list:
        for gw in gws:
            try:
                file_name = f"gw{gw}.csv"
                path = content / "Fantasy-Premier-League" / "data" / season / "gws" / file_name

                df = pd.read_csv(path, encoding='utf-8')
                df['season'] = season

                if not df.empty:
                    dfs.append(df)

            except Exception as e:
                print(e)
                pass

    if not dfs:
        return pd.DataFrame()

    return pd.concat(dfs, axis=0, ignore_index=True)

In [29]:
data = data_import(season_list=seasons)

[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw25.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw26.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw27.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw28.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw29.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw30.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw31.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw32.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw33.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw34.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw35.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw36.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw37.csv'
[Errno 2] No such file or directory: '..\\Fantasy-Premier-League\\data\\2025-26\\gws\\gw38.csv'

In [30]:
data.head()

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,season,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts,modified,mng_clean_sheets,mng_draw,mng_goals_scored,mng_loss,mng_underdog_draw,mng_underdog_win,mng_win,clearances_blocks_interceptions,defensive_contribution,recoveries,tackles
0,Eric Bailly,DEF,Man Utd,0.0,0,0,0,0,0.0,286,6,0,0,0.0,0.0,2021-08-14T11:30:00Z,0,10,0,0,0,0,1,0,9363,1,5,0.0,0,0,0,0,50,True,0,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Keinan Davis,FWD,Aston Villa,0.4,0,0,0,0,0.0,49,8,0,0,0.0,0.0,2021-08-14T14:00:00Z,0,18,0,0,0,0,1,0,169789,2,3,0.0,0,0,0,0,45,False,0,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ayotomiwa Dele-Bashiru,MID,Watford,0.0,0,0,0,0,0.0,394,8,0,0,0.0,0.0,2021-08-14T14:00:00Z,0,2,0,0,0,0,1,0,4092,2,3,0.0,0,0,0,0,45,True,0,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,James Ward-Prowse,MID,Southampton,2.3,0,0,20,0,30.5,341,4,3,0,5.2,21.6,2021-08-14T14:00:00Z,90,8,0,0,0,0,1,0,299682,1,3,0.0,2,0,0,0,65,False,0,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bruno Miguel Borges Fernandes,MID,Man Utd,4.4,0,3,61,0,35.9,277,6,1,3,20.1,106.2,2021-08-14T11:30:00Z,90,10,0,0,0,0,1,0,3381004,1,5,59.0,20,0,0,0,120,True,0,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
def sort_data(df:pd.DataFrame)->pd.DataFrame:
  return df.sort_values(by=["name", "kickoff_time", "fixture", "season"])

In [34]:
data = sort_data(df=data)

In [35]:
data.head()

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,season,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts,modified,mng_clean_sheets,mng_draw,mng_goals_scored,mng_loss,mng_underdog_draw,mng_underdog_win,mng_win,clearances_blocks_interceptions,defensive_contribution,recoveries,tackles
98924,Aaron Anselmino,DEF,Chelsea,1.8,0,0,0,0,0.0,774,242,0,0,0.0,0.0,2025-02-14T20:00:00Z,0,5,0,0,0,0,25,0,0,0,3,0.0,0,0,0,0,40,False,0,2024-25,0.0,0.0,0.0,0.0,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
99717,Aaron Anselmino,DEF,Chelsea,0.5,0,0,0,0,0.0,774,252,0,0,0.0,0.0,2025-02-22T17:30:00Z,0,2,0,0,0,0,26,0,156,1,2,0.0,0,82,92,10,40,False,0,2024-25,0.0,0.0,0.0,0.0,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
100500,Aaron Anselmino,DEF,Chelsea,1.0,0,0,0,0,0.0,774,268,0,0,0.0,0.0,2025-02-25T20:15:00Z,0,17,0,0,0,0,27,0,236,0,4,0.0,0,29,58,29,40,True,0,2024-25,0.0,0.0,0.0,0.0,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
101288,Aaron Anselmino,DEF,Chelsea,0.5,0,0,0,0,0.0,774,273,0,0,0.0,0.0,2025-03-09T14:00:00Z,0,11,0,0,0,0,28,0,325,0,1,0.0,0,21,52,31,40,True,0,2024-25,0.0,0.0,0.0,0.0,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
101946,Aaron Anselmino,DEF,Chelsea,0.0,0,0,0,0,0.0,774,281,0,0,0.0,0.0,2025-03-16T13:30:00Z,0,1,0,0,0,0,29,0,436,0,1,0.0,0,4,31,27,40,False,0,2024-25,0.0,0.0,0.0,0.0,0.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [36]:
data.shape

(127465, 53)

In [38]:
filename = "FPL_data_untidy.csv"
data.to_csv(filename, index=False)