In [811]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import time
import seaborn as sns
import sys
from pyprojroot import here
from warnings import filterwarnings
filterwarnings("ignore")

sys.path.append(str(here("Scripts")))
from utils import data_import, sort_data, club_data_import

In [812]:
seasons = ['2021-22', '2022-23', '2023-24', '2024-25', '2025-26']

In [814]:
club_data = club_data_import(seasons)

In [815]:
club_data.columns = club_data.columns.str.lower()
club_data.head()

,div,date,time,hometeam,awayteam,fthg,ftag,ftr,hthg,htag,htr,referee,hs,as,hst,ast,hf,af,hc,ac,hy,ay,hr,ar,b365h,b365d,b365a,bwh,bwd,bwa,iwh,iwd,iwa,psh,psd,psa,whh,whd,wha,vch,vcd,vca,maxh,maxd,maxa,avgh,avgd,avga,b365>2.5,b365<2.5,p>2.5,p<2.5,max>2.5,max<2.5,avg>2.5,avg<2.5,ahh,b365ahh,b365aha,pahh,paha,maxahh,maxaha,avgahh,avgaha,b365ch,b365cd,b365ca,bwch,bwcd,bwca,iwch,iwcd,iwca,psch,pscd,psca,whch,whcd,whca,vcch,vccd,vcca,maxch,maxcd,maxca,avgch,avgcd,avgca,b365c>2.5,b365c<2.5,pc>2.5,pc<2.5,maxc>2.5,maxc<2.5,avgc>2.5,avgc<2.5,ahch,b365cahh,b365caha,pcahh,pcaha,maxcahh,maxcaha,avgcahh,avgcaha,season_id,bfh,bfd,bfa,1xbh,1xbd,1xba,bfeh,bfed,bfea,bfe>2.5,bfe<2.5,bfeahh,bfeaha,bfch,bfcd,bfca,1xbch,1xbcd,1xbca,bfech,bfecd,bfeca,bfec>2.5,bfec<2.5,bfecahh,bfecaha,bfdh,bfdd,bfda,bmgmh,bmgmd,bmgma,bvh,bvd,bva,clh,cld,cla,lbh,lbd,lba,bfdch,bfdcd,bfdca,bmgmch,bmgmcd,bmgmca,bvch,bvcd,bvca,clch,clcd,clca,lbch,lbcd,lbca
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,H,M Oliver,8,22,3,4,12,8,2,5,0,0,0,0,4.00,3.40,1.95,4.00,3.50,1.95,3.80,3.40,2.05,4.05,3.46,2.05,4.00,3.40,1.90,4.10,3.40,2.00,4.62,3.72,2.10,4.02,3.43,2.02,2.10,1.72,2.22,1.73,2.26,1.83,2.16,1.73,0.50,1.86,2.07,1.88,2.06,2.05,2.08,1.87,2.03,3.80,3.25,2.05,3.80,3.3,2.05,3.80,3.25,2.10,3.94,3.33,2.13,3.90,3.00,2.05,3.90,3.25,2.10,4.20,3.50,2.18,3.89,3.28,2.10,2.37,1.57,2.44,1.62,2.47,1.75,2.33,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,H,P Tierney,16,10,8,3,11,9,5,4,1,2,0,0,1.53,4.50,5.75,1.53,4.50,5.75,1.55,4.40,5.75,1.56,4.57,5.96,1.52,4.33,5.80,1.55,4.40,6.00,1.59,4.65,6.35,1.55,4.48,5.87,1.61,2.30,1.67,2.32,1.71,2.38,1.65,2.29,-1.00,1.95,1.98,1.96,1.96,2.00,2.01,1.93,1.96,1.61,4.20,5.25,1.62,4.1,5.25,1.65,4.20,4.90,1.67,4.20,5.40,1.57,4.20,5.50,1.65,4.10,5.25,1.71,4.33,5.80,1.64,4.19,5.22,1.66,2.20,1.70,2.27,1.75,2.37,1.67,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,H,D Coote,14,14,3,8,10,7,7,6,2,1,0,0,3.10,3.10,2.45,3.20,3.10,2.40,3.15,3.05,2.45,3.30,3.12,2.51,3.20,3.00,2.45,3.13,3.10,2.45,3.33,3.20,2.60,3.19,3.09,2.49,2.50,1.53,2.56,1.56,2.56,1.63,2.46,1.57,0.25,1.80,2.14,1.83,2.12,1.83,2.17,1.79,2.12,3.10,3.10,2.45,3.25,3.1,2.40,3.10,3.05,2.45,3.27,3.14,2.51,3.10,3.00,2.45,3.13,3.13,2.50,3.35,3.20,2.56,3.19,3.10,2.48,2.30,1.61,2.33,1.67,2.42,1.71,2.34,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,H,J Moss,13,4,6,1,15,11,5,2,0,0,0,0,1.25,5.75,13.00,1.28,5.75,10.50,1.25,6.00,13.00,1.26,6.24,12.74,1.25,5.50,13.00,1.25,5.75,13.00,1.30,6.30,15.00,1.26,5.92,12.80,1.80,2.00,1.80,2.09,1.84,2.12,1.79,2.06,-1.50,1.84,2.09,1.79,2.12,1.93,2.12,1.83,2.07,1.30,5.25,11.00,1.33,5.0,10.00,1.30,5.25,11.00,1.34,5.40,11.00,1.30,5.25,10.00,1.33,5.00,11.00,1.36,5.50,11.50,1.33,5.17,10.58,1.90,1.90,1.93,1.98,1.96,2.07,1.90,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,A,A Madley,14,6,6,3,13,15,6,8,2,0,0,0,1.90,3.50,4.00,1.95,3.50,3.90,1.95,3.45,3.95,2.01,3.56,4.10,1.95,3.40,4.00,1.95,3.40,4.10,2.04,3.66,4.25,1.97,3.53,4.04,2.00,1.80,2.14,1.78,2.14,1.85,2.07,1.79,-0.50,2.00,1.93,2.01,1.92,2.01,1.97,1.96,1.92,2.00,3.40,3.90,2.05,3.4,3.75,2.00,3.35,4.00,2.05,3.45,4.07,1.95,3.40,3.90,2.00,3.30,4.20,2.12,3.50,4.20,2.04,3.39,3.95,2.20,1.66,2.28,1.69,2.34,1.77,2.24,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [816]:
club_data.shape

(1781, 163)

In [817]:
club_data.isna().mean()[club_data.isna().mean()>0]

bwh     0.080292
bwd     0.080292
bwa     0.080292
iwh     0.462100
iwd     0.462100
          ...
clcd    0.875912
clca    0.875912
lbch    0.875912
lbcd    0.875912
lbca    0.875912
Length: 100, dtype: float64

In [818]:
player_data = data_import(season_list=seasons)

In [819]:
player_data.head()

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,season_id,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts,mng_clean_sheets,mng_draw,mng_goals_scored,mng_loss,mng_underdog_draw,mng_underdog_win,mng_win,modified,clearances_blocks_interceptions,defensive_contribution,recoveries,tackles
0,Eric Bailly,DEF,Man Utd,0.0,0,0,0,0,0.0,286,6,0,0,0.0,0.0,2021-08-14T11:30:00Z,0,10,0,0,0,0,1,0,9363,1,5,0.0,0,0,0,0,50,True,0,1,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Keinan Davis,FWD,Aston Villa,0.4,0,0,0,0,0.0,49,8,0,0,0.0,0.0,2021-08-14T14:00:00Z,0,18,0,0,0,0,1,0,169789,2,3,0.0,0,0,0,0,45,False,0,1,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ayotomiwa Dele-Bashiru,MID,Watford,0.0,0,0,0,0,0.0,394,8,0,0,0.0,0.0,2021-08-14T14:00:00Z,0,2,0,0,0,0,1,0,4092,2,3,0.0,0,0,0,0,45,True,0,1,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,James Ward-Prowse,MID,Southampton,2.3,0,0,20,0,30.5,341,4,3,0,5.2,21.6,2021-08-14T14:00:00Z,90,8,0,0,0,0,1,0,299682,1,3,0.0,2,0,0,0,65,False,0,1,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bruno Miguel Borges Fernandes,MID,Man Utd,4.4,0,3,61,0,35.9,277,6,1,3,20.1,106.2,2021-08-14T11:30:00Z,90,10,0,0,0,0,1,0,3381004,1,5,59.0,20,0,0,0,120,True,0,1,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [820]:
player_data = sort_data(df=player_data)

In [821]:
player_data.head()

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,season_id,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts,mng_clean_sheets,mng_draw,mng_goals_scored,mng_loss,mng_underdog_draw,mng_underdog_win,mng_win,modified,clearances_blocks_interceptions,defensive_contribution,recoveries,tackles
0,Aaron Anselmino,DEF,Chelsea,1.8,0,0,0,0,0.0,774,242,0,0,0.0,0.0,2025-02-14T20:00:00Z,0,5,0,0,0,0,25,0,0,0,3,0.0,0,0,0,0,40,False,0,25,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN
1,Aaron Anselmino,DEF,Chelsea,0.5,0,0,0,0,0.0,774,252,0,0,0.0,0.0,2025-02-22T17:30:00Z,0,2,0,0,0,0,26,0,156,1,2,0.0,0,82,92,10,40,False,0,26,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN
2,Aaron Anselmino,DEF,Chelsea,1.0,0,0,0,0,0.0,774,268,0,0,0.0,0.0,2025-02-25T20:15:00Z,0,17,0,0,0,0,27,0,236,0,4,0.0,0,29,58,29,40,True,0,27,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN
3,Aaron Anselmino,DEF,Chelsea,0.5,0,0,0,0,0.0,774,273,0,0,0.0,0.0,2025-03-09T14:00:00Z,0,11,0,0,0,0,28,0,325,0,1,0.0,0,21,52,31,40,True,0,28,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN
4,Aaron Anselmino,DEF,Chelsea,0.0,0,0,0,0,0.0,774,281,0,0,0.0,0.0,2025-03-16T13:30:00Z,0,1,0,0,0,0,29,0,436,0,1,0.0,0,4,31,27,40,False,0,29,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN

In [822]:
player_data.shape

(127465, 54)

In [823]:
player_data.team.unique()

<ArrowStringArray>
[       'Chelsea',       'Brighton',       'West Ham',      'Brentford',
        'Burnley',        'Arsenal',    'Southampton',      'Newcastle',
    'Aston Villa',        'Man Utd',        'Everton',     'Sunderland',
       'Man City',      'Leicester',        'Norwich',  'Sheffield Utd',
          'Leeds',        'Watford',    'Bournemouth', 'Crystal Palace',
         'Wolves',         'Fulham',          'Luton',      'Liverpool',
          'Spurs',  'Nott'm Forest',        'Ipswich']
Length: 27, dtype: str

In [824]:
club_data.hometeam.unique()

<ArrowStringArray>
[       'Brentford',       'Man United',          'Burnley',
          'Chelsea',          'Everton',        'Leicester',
          'Watford',          'Norwich',        'Newcastle',
        'Tottenham',        'Liverpool',      'Aston Villa',
   'Crystal Palace',            'Leeds',         'Man City',
         'Brighton',      'Southampton',           'Wolves',
          'Arsenal',         'West Ham',           'Fulham',
      'Bournemouth',    'Nott'm Forest', 'Sheffield United',
            'Luton',          'Ipswich',       'Sunderland']
Length: 27, dtype: str

In [825]:
[t for t in club_data.hometeam.unique() if t not in player_data.team.unique()]

['Man United', 'Tottenham', 'Sheffield United']

In [826]:
club_data = club_data.replace({
    'Man United' : "Man Utd",
    'Tottenham': "Spurs",
    'Sheffield United' : "Sheffield Utd"})

In [827]:
[t for t in club_data.hometeam.unique() if t not in player_data.team.unique()]

[]

In [828]:
player_data["kickoff_time"] = pd.to_datetime(player_data.kickoff_time).dt.tz_localize(None)


club_data["kickoff_time"] = pd.to_datetime(
    club_data['date'].astype(str) + ' ' + club_data['time'].astype(str),
    dayfirst=True)

In [829]:
player_data.loc[
    (player_data.team == "Chelsea") &
    (player_data.was_home == True) &
    (player_data.season_id == "2024-25") &
    (player_data.kickoff_time == "2024-08-18 15:30:00"),
    ["team", "season_id", "kickoff_time"]].head(1)

         team season_id        kickoff_time
4914  Chelsea   2024-25 2024-08-18 15:30:00

In [830]:
club_data.loc[(club_data.hometeam=="Chelsea") &
              (club_data.season_id=="2024-25") &
              (club_data.kickoff_time == "2024-08-18 15:30:00"),
              ["hometeam", "season_id", "kickoff_time"]]

Empty DataFrame
Columns: [hometeam, season_id, kickoff_time]
Index: []

In [831]:
# 1. Metadane i Identyfikacja (Klucze do merge'a)
meta_cols = ['div', 'date', 'time', 'team', 'opp', 'season_id', 'kickoff_time']

# 2. Wyniki Meczowe (Podstawowe rezultaty)
result_cols = ['gf', 'ga', 'ftr', 'hthg', 'htag', 'htr', 'referee']

# 3. Statystyki Wydajności (Kluczowe dla FPL)
# HS/AS - Shots, HST/AST - Shots on Target, HC/AC - Corners, HY/AY - Yellow Cards, HR/AR - Red Cards
performance_stats = [
    'hs', 'as', 'hst', 'ast', 'hf', 'af',
    'hc', 'ac', 'hy', 'ay', 'hr', 'ar'
]

# 4. Kursy 1X2 (Otwarcie i Główny Rynek)
# B365 - Bet365, BW - Bet&Win, IW - Interwetten, PS - Pinnacle, WH - William Hill, VC - VC Bet
main_odds_1x2 = [
    'b365h', 'b365d', 'b365a', 'bwh', 'bwd', 'bwa', 'iwh', 'iwd', 'iwa',
    'psh', 'psd', 'psa', 'whh', 'whd', 'wha', 'vch', 'vcd', 'vca',
    'maxh', 'maxd', 'maxa', 'avgh', 'avgd', 'avga'
]

# 5. Kursy Over/Under 2.5 Gola
ou_odds = [
    'b365>2.5', 'b365<2.5', 'p>2.5', 'p<2.5',
    'max>2.5', 'max<2.5', 'avg>2.5', 'avg<2.5'
]

# 6. Kursy Asian Handicap
asian_odds = [
    'ahh', 'b365ahh', 'b365aha', 'pahh', 'paha',
    'maxahh', 'maxaha', 'avgahh', 'avgaha'
]

# 7. Kursy Zamykające (Closing Odds - z literą 'c')
closing_odds = [
    'b365ch', 'b365cd', 'b365ca', 'bwch', 'bwcd', 'bwca', 'iwch', 'iwcd', 'iwca',
    'psch', 'pscd', 'psca', 'whch', 'whcd', 'whca', 'vcch', 'vccd', 'vcca',
    'maxch', 'maxcd', 'maxca', 'avgch', 'avgcd', 'avgca', 'ahch', 'b365cahh',
    'b365caha', 'pcahh', 'pcaha', 'maxcahh', 'maxcaha', 'avgcahh', 'avgcaha',
    'b365c>2.5', 'b365c<2.5', 'pc>2.5', 'pc<2.5', 'maxc>2.5', 'maxc<2.5', 'avgc>2.5', 'avgc<2.5'
]

# 8. Pozostali Bukmacherzy i Giełdy (Betfair, 1xBet, BetMGM, itp.)
extra_bookies = [
    'bfh', 'bfd', 'bfa', '1xbh', '1xbd', '1xba', 'bfeh', 'bfed', 'bfea',
    'bfe>2.5', 'bfe<2.5', 'bfeahh', 'bfeaha', 'bfch', 'bfcd', 'bfca',
    '1xbch', '1xbcd', '1xbca', 'bfech', 'bfecd', 'bfeca', 'bfec>2.5',
    'bfec<2.5', 'bfecahh', 'bfecaha', 'bfdh', 'bfdd', 'bfda', 'bmgmh',
    'bmgmd', 'bmgma', 'bvh', 'bvd', 'bva', 'clh', 'cld', 'cla', 'lbh',
    'lbd', 'lba', 'bfdch', 'bfdcd', 'bfdca', 'bmgmch', 'bmgmcd', 'bmgmca',
    'bvch', 'bvcd', 'bvca', 'clch', 'clcd', 'clca', 'lbch', 'lbcd', 'lbca'
]

In [832]:
mapping = {
        'team': ('hometeam', 'awayteam'),
        'opp': ('awayteam', 'hometeam'),
        'gf': ('fthg', 'ftag'),
        'ga': ('ftag', 'fthg'),
        'sh': ('hs', 'as'),
        'sht': ('hst', 'ast'),
        'corners': ('hc', 'ac'),
        'yc': ('hy', 'ay'),
        'rc': ('hr', 'ar'),
        'fouls': ('hf', 'af'),
        # --- BET365 1X2 ---
        'b365_win': ('b365h', 'b365a'),
        'b365_draw': ('b365d', 'b365d'),
        'b365_loss': ('b365a', 'b365h'),
        # --- BET365 OVER/UNDER 2.5 ---
        'b365_o25': ('b365>2.5', 'b365>2.5'),
        'b365_u25': ('b365<2.5', 'b365<2.5'),
        # --- BET365 ASIAN HANDICAP ---
        'b365_ah_line': ('ahh', 'ahh'),
        'b365_ah_team': ('b365ahh', 'b365aha'),
        'b365_ah_opp': ('b365aha', 'b365ahh')
    }

In [833]:
def transform_match_data(df:pd.DataFrame,
                         mapping:dict[str, tuple[str, str]] | None = None)->pd.DataFrame:
    if mapping is None:
       return df.copy()

    common = ['date', 'time', 'kickoff_time', 'season_id', 'div']


    def build_view(is_home):
        idx = 0 if is_home else 1
        side_df = df[common].copy()
        for new_col, pairs in mapping.items():
            source = pairs[idx]
            if source in df.columns:
                side_df[new_col] = df[source]
        side_df['was_home'] = is_home
        return side_df

    long_df = pd.concat([build_view(True), build_view(False)], ignore_index=True)

    if 'b365_ah_line' in long_df.columns:
        long_df.loc[~long_df['was_home'], 'b365_ah_line'] *= -1

    return long_df.sort_values(['kickoff_time', 'team']).reset_index(drop=True)

In [834]:
club_data = transform_match_data(club_data, mapping=mapping)

In [835]:
player_data.head()

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,season_id,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts,mng_clean_sheets,mng_draw,mng_goals_scored,mng_loss,mng_underdog_draw,mng_underdog_win,mng_win,modified,clearances_blocks_interceptions,defensive_contribution,recoveries,tackles
0,Aaron Anselmino,DEF,Chelsea,1.8,0,0,0,0,0.0,774,242,0,0,0.0,0.0,2025-02-14 20:00:00,0,5,0,0,0,0,25,0,0,0,3,0.0,0,0,0,0,40,False,0,25,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN
1,Aaron Anselmino,DEF,Chelsea,0.5,0,0,0,0,0.0,774,252,0,0,0.0,0.0,2025-02-22 17:30:00,0,2,0,0,0,0,26,0,156,1,2,0.0,0,82,92,10,40,False,0,26,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN
2,Aaron Anselmino,DEF,Chelsea,1.0,0,0,0,0,0.0,774,268,0,0,0.0,0.0,2025-02-25 20:15:00,0,17,0,0,0,0,27,0,236,0,4,0.0,0,29,58,29,40,True,0,27,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN
3,Aaron Anselmino,DEF,Chelsea,0.5,0,0,0,0,0.0,774,273,0,0,0.0,0.0,2025-03-09 14:00:00,0,11,0,0,0,0,28,0,325,0,1,0.0,0,21,52,31,40,True,0,28,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN
4,Aaron Anselmino,DEF,Chelsea,0.0,0,0,0,0,0.0,774,281,0,0,0.0,0.0,2025-03-16 13:30:00,0,1,0,0,0,0,29,0,436,0,1,0.0,0,4,31,27,40,False,0,29,2024-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN

In [836]:
club_data.head()

,date,time,kickoff_time,season_id,div,team,opp,gf,ga,sh,sht,corners,yc,rc,fouls,b365_win,b365_draw,b365_loss,b365_o25,b365_u25,b365_ah_line,b365_ah_team,b365_ah_opp,was_home
0,13/08/2021,20:00,2021-08-13 20:00:00,2021-22,E0,Arsenal,Brentford,0,2,22,4,5,0,0,8,1.95,3.4,4.00,2.10,1.72,-0.50,2.07,1.86,False
1,13/08/2021,20:00,2021-08-13 20:00:00,2021-22,E0,Brentford,Arsenal,2,0,8,3,2,0,0,12,4.00,3.4,1.95,2.10,1.72,0.50,1.86,2.07,True
2,14/08/2021,12:30,2021-08-14 12:30:00,2021-22,E0,Leeds,Man Utd,1,5,10,3,4,2,0,9,5.75,4.5,1.53,1.61,2.30,1.00,1.98,1.95,False
3,14/08/2021,12:30,2021-08-14 12:30:00,2021-22,E0,Man Utd,Leeds,5,1,16,8,5,1,0,11,1.53,4.5,5.75,1.61,2.30,-1.00,1.95,1.98,True
4,14/08/2021,15:00,2021-08-14 15:00:00,2021-22,E0,Aston Villa,Watford,2,3,11,2,4,1,0,13,2.37,3.2,3.10,2.00,1.80,-0.25,2.10,1.83,False

In [837]:
player_data = player_data.convert_dtypes()
club_data = club_data.convert_dtypes()

In [838]:
cols_to_keep = list(mapping.keys()) + meta_cols + result_cols +  performance_stats + ['was_home']

In [839]:
meta_cols

['div', 'date', 'time', 'team', 'opp', 'season_id', 'kickoff_time']

In [840]:
club_data.drop(columns=[c for c in club_data.columns if c not in cols_to_keep]+["div", "date", "time"], inplace=True)

In [841]:
club_data.shape, player_data.shape

((3562, 21), (127465, 54))

In [842]:
[c for c in club_data.columns if c in player_data.columns]

['kickoff_time', 'season_id', 'team', 'was_home']

In [843]:
player_data = player_data.assign(match_date=player_data.kickoff_time.dt.date)

club_data = club_data.assign(match_date=club_data.kickoff_time.dt.date)

In [844]:
data = pd.merge(
    player_data,
    club_data,
    on=['team', 'season_id', 'was_home', 'match_date'],
    how='left',
    suffixes=("_player", "_match")
)

In [845]:
data.shape

(127465, 73)

In [846]:
data.head()

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time_player,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,season_id,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts,mng_clean_sheets,mng_draw,mng_goals_scored,mng_loss,mng_underdog_draw,mng_underdog_win,mng_win,modified,clearances_blocks_interceptions,defensive_contribution,recoveries,tackles,match_date,kickoff_time_match,opp,gf,ga,sh,sht,corners,yc,rc,fouls,b365_win,b365_draw,b365_loss,b365_o25,b365_u25,b365_ah_line,b365_ah_team,b365_ah_opp
0,Aaron Anselmino,DEF,Chelsea,1.8,0,0,0,0,0.0,774,242,0,0,0.0,0.0,2025-02-14 20:00:00,0,5,0,0,0,0,25,0,0,0,3,0,0,0,0,0,40,False,0,25,2024-25,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,False,<NA>,<NA>,<NA>,<NA>,2025-02-14,2025-02-14 20:00:00,Brighton,0,3,8,0,9,2,0,15,2.45,3.6,2.7,1.57,2.38,-0.25,2.08,1.73
1,Aaron Anselmino,DEF,Chelsea,0.5,0,0,0,0,0.0,774,252,0,0,0.0,0.0,2025-02-22 17:30:00,0,2,0,0,0,0,26,0,156,1,2,0,0,82,92,10,40,False,0,26,2024-25,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,False,<NA>,<NA>,<NA>,<NA>,2025-02-22,2025-02-22 17:30:00,Aston Villa,1,2,15,7,3,3,0,16,2.6,3.4,2.63,1.57,2.38,-0.0,1.92,1.98
2,Aaron Anselmino,DEF,Chelsea,1.0,0,0,0,0,0.0,774,268,0,0,0.0,0.0,2025-02-25 20:15:00,0,17,0,0,0,0,27,0,236,0,4,0,0,29,58,29,40,True,0,27,2024-25,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,False,<NA>,<NA>,<NA>,<NA>,2025-02-25,2025-02-25 20:15:00,Southampton,4,0,19,10,4,1,0,6,1.17,8.0,13.0,1.29,3.75,-2.25,2.0,1.93
3,Aaron Anselmino,DEF,Chelsea,0.5,0,0,0,0,0.0,774,273,0,0,0.0,0.0,2025-03-09 14:00:00,0,11,0,0,0,0,28,0,325,0,1,0,0,21,52,31,40,True,0,28,2024-25,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,False,<NA>,<NA>,<NA>,<NA>,2025-03-09,2025-03-09 14:00:00,Leicester,1,0,20,7,12,1,0,12,1.18,8.0,12.0,1.33,3.2,-2.0,1.95,1.95
4,Aaron Anselmino,DEF,Chelsea,0.0,0,0,0,0,0.0,774,281,0,0,0.0,0.0,2025-03-16 13:30:00,0,1,0,0,0,0,29,0,436,0,1,0,0,4,31,27,40,False,0,29,2024-25,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,False,<NA>,<NA>,<NA>,<NA>,2025-03-16,2025-03-16 13:30:00,Arsenal,0,1,8,2,4,3,0,13,4.5,3.6,1.8,1.86,1.92,0.75,1.84,2.06

In [847]:
data.shape[0] == player_data.shape[0]

True

In [848]:
player_data.loc[(player_data.name=="Aaron Anselmino") & (data.season_id=="2024-25"), ["GW"]]==data.loc[(data.name=="Aaron Anselmino") & (data.season_id=="2024-25"), ["GW"]]

      GW
0   True
1   True
2   True
3   True
4   True
5   True
6   True
7   True
8   True
9   True
10  True
11  True
12  True
13  True

In [849]:
data.isna().mean()[data.isna().mean()>0].sort_values(ascending=False)

mng_loss                           0.894661
mng_clean_sheets                   0.894661
mng_draw                           0.894661
mng_underdog_draw                  0.894661
mng_underdog_win                   0.894661
mng_win                            0.894661
mng_goals_scored                   0.894661
tackles                            0.857349
recoveries                         0.857349
defensive_contribution             0.857349
clearances_blocks_interceptions    0.857349
modified                           0.640780
expected_goals                     0.199639
expected_assists                   0.199639
expected_goal_involvements         0.199639
starts                             0.199639
expected_goals_conceded            0.199639
b365_o25                           0.000463
b365_u25                           0.000463
dtype: float64

In [850]:
def duplicated_cols(df:pd.DataFrame)->list[str]:
    return df.columns[df.T.duplicated(keep=False)].tolist()

In [851]:
dup_cols = duplicated_cols(df=data)

In [852]:
dup_cols

['round', 'GW']

In [853]:
data.drop(columns=dup_cols[0], inplace=True)

In [854]:
data_to_save = {
    "FPL_data_untidy": data,
    "club_data": club_data,
    "player_data": player_data
}
for name, df in data_to_save.items():
    path = f"../../Data/{name}.parquet"
    df.to_parquet(path,
                 engine='pyarrow',
                 index=False)

0       2021-08-13
1       2021-08-13
2       2021-08-14
3       2021-08-14
4       2021-08-14
           ...
3557    2026-02-11
3558    2026-02-12
3559    2026-02-12
3560    2026-02-18
3561    2026-02-18
Name: match_date, Length: 3562, dtype: object